Guard against running from master branch

diff --git a/roles/git/files/bin/git-pr-merged b/roles/git/files/bin/git-pr-merged
--- a/roles/git/files/bin/git-pr-merged
+++ b/roles/git/files/bin/git-pr-merged
@@ -15,6 +15,12 @@ else
   local branch=$(git symbolic-ref --short -q HEAD)
 fi
 
+if [[ $branch -eq "master" ]]; then
+  echo >&2 "\033[31;1m==>\033[0;1m Error! Currently on master branch.\033[0m"
+  echo >&2 "Check out your feature branch via \`git checkout\` and run me again."
+  exit 1
+fi
+
 git checkout master
 git pull --rebase
 git db $branch
